# monitoring/prometheus/alerts.yml
groups:
  - name: wapro-network-alerts
    rules:
      - alert: ServiceDown
        expr: up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.instance }} is down"

      - alert: DatabaseConnectionFailed
        expr: database_connection_status == 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Database connection failed for {{ $labels.database }}"

      - alert: PrinterOffline
        expr: printer_available == 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Printer {{ $labels.printer_name }} is offline"