global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'wapro-network'
    static_configs:
      - targets: ['rpi-server:8081']
    scrape_interval: 10s
    metrics_path: '/api/metrics'

  - job_name: 'zebra-printers'
    static_configs:
      - targets:
          - 'zebra-printer-1:8080'
          - 'zebra-printer-2:8080'
    scrape_interval: 15s
    metrics_path: '/api/metrics'